default: &default
  adapter: mysql2
  encoding: utf8mb4
  username: blog
  password: 1234
  host: localhost
  port: 3306
  read_timeout: 40
  connect_timeout: 30
  reconnect: true
  pool: 64
development:
  <<: *default
  database: blog
staging:
  <<: *default
  database: blog
test:
  <<: *default
  database: blog